[package]
name = "cross233-qcp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "QCP reliable-UDP transport for cross233"

[dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
socket2 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
rand = { workspace = true }
